import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import app from '../src/index.js';
import {database} from './db.mjs';
import {buildMime,cleanEmailHtml,parseStoredMessage} from '../src/lib/mail.js';
import {hashPassword} from '../src/lib/security.js';
const db=database(),objects=new Map();let failStorage=false,providerCalls=0,providerMode='ok',lastPayload;
const env={DB:db,SETUP_SECRET:'test-setup-secret',RESEND_API_KEY:'test-key-not-real',MAIL_STORAGE:{async put(k,v){if(failStorage)throw Error('Storage offline');objects.set(k,v)},async get(k){const value=objects.get(k);return value?{arrayBuffer:async()=>value}:null},async delete(k){objects.delete(k)}}};
let cookie='';
async function request(url,method='GET',body,headers={}){const h={'x-sfm-request':'1',cookie,...headers};if(body&&!(body instanceof FormData))h['content-type']='application/json';const r=await app.fetch(new Request('https://mail.test'+url,{method,headers:h,body:body instanceof FormData?body:body?JSON.stringify(body):undefined}),env);return {r,data:await r.json()};}
function compose(key,to='reader@skyfirst.io.vn'){const f=new FormData();f.set('requestId',key);f.set('mailboxId','1');f.set('to',to);f.set('subject','Kiểm thử tiếng Việt');f.set('text','Nội dung thư');return f;}
test('mail API and persisted delivery',async t=>{
 const originalFetch=globalThis.fetch;globalThis.fetch=async(url,opts)=>{assert.equal(url,'https://api.resend.com/emails');providerCalls++;lastPayload=JSON.parse(opts.body);assert.ok(opts.headers['Idempotency-Key']);if(providerMode==='timeout')throw Error('Connection lost');return Response.json({id:'provider-'+providerCalls});};
 try{
 await t.test('bootstrap locked, correct secret creates root',async()=>{const b={email:'admin@skyfirst.io.vn',displayName:'Root',password:'mail-test-password'};assert.equal((await request('/api/bootstrap','POST',b)).r.status,403);const x=await request('/api/bootstrap','POST',b,{'x-setup-secret':env.SETUP_SECRET});assert.equal(x.r.status,200);cookie=x.r.headers.get('set-cookie').split(';')[0];const p=await hashPassword('reader-password');db.sql.prepare('INSERT INTO users(email,display_name,password_salt,password_hash,password_iterations) VALUES(?,?,?,?,?)').run('reader@skyfirst.io.vn','Reader',p.salt,p.hash,p.iterations);db.sql.exec("INSERT INTO mailboxes(user_id,address,display_name) VALUES(2,'reader@skyfirst.io.vn','Reader')");});
 await t.test('cross-site writes blocked',async()=>assert.equal((await request('/api/logout','POST',{}, {origin:'https://evil.test'})).r.status,403));
 await t.test('internal send commits both mailboxes once',async()=>{const x=await request('/api/compose','POST',compose('internal-00000001'));assert.equal(x.r.status,200,JSON.stringify(x.data));assert.equal(db.sql.prepare('SELECT count(*) n FROM messages').get().n,2);const again=await request('/api/compose','POST',compose('internal-00000001'));assert.equal(again.r.status,200);assert.equal(db.sql.prepare('SELECT count(*) n FROM messages').get().n,2);assert.equal(providerCalls,0)});
 await t.test('same id cannot change content',async()=>{const f=compose('internal-00000001');f.set('subject','Changed');assert.equal((await request('/api/compose','POST',f)).r.status,409)});
 await t.test('R2 failure occurs before external send',async()=>{db.sql.exec("UPDATE managed_domains SET send_enabled=1 WHERE domain='skyfirst.io.vn'");failStorage=true;const x=await request('/api/compose','POST',compose('storage-fail-0001','external@example.test'));failStorage=false;assert.equal(x.r.status,502);assert.equal(providerCalls,0)});
 await t.test('inline images reach provider; BCC absent from MIME headers',async()=>{const f=compose('external-inline01','external@example.test');f.set('bcc','hidden@example.test');f.set('html','<p><img src="cid:logo-one"></p>');f.append('inlineAttachments',new File([new Uint8Array([1,2,3])],'logo.png',{type:'image/png'}));f.set('inlineCidMap',JSON.stringify([{name:'logo.png',cid:'logo-one'}]));const x=await request('/api/compose','POST',f);assert.equal(x.r.status,200,JSON.stringify(x.data));assert.equal(providerCalls,1);assert.equal(lastPayload.attachments[0].content_id,'logo-one');const op=db.sql.prepare('SELECT * FROM send_operations WHERE id=?').get(x.data.operationId);assert.ok(!new TextDecoder().decode(objects.get(op.storage_key)).includes('Bcc:'));});
 await t.test('provider timeout blocks dangerous resend',async()=>{providerMode='timeout';const x=await request('/api/compose','POST',compose('uncertain-000001','external@example.test'));assert.equal(x.data.status,'uncertain');const calls=providerCalls;assert.equal((await request('/api/compose','POST',compose('uncertain-000001','external@example.test'))).r.status,409);assert.equal(providerCalls,calls);providerMode='ok';});
 await t.test('reader cannot fetch another mailbox message',async()=>{const login=await request('/api/login','POST',{email:'reader@skyfirst.io.vn',password:'reader-password'});const rootCookie=cookie;cookie=login.r.headers.get('set-cookie').split(';')[0];assert.equal((await request('/api/messages/1')).r.status,404);assert.equal((await request('/api/admin/send-operations')).r.status,403);cookie=rootCookie;});
 await t.test('domain disabled remains disabled',async()=>{db.sql.exec("UPDATE managed_domains SET send_enabled=0 WHERE domain='skyfirst.io.vn'");assert.equal((await request('/api/compose','POST',compose('disabled-0000001','external@example.test'))).r.status,400)});
 await t.test('inbound retry stored once, header date normalized',async()=>{const raw=await buildMime({from:'other@example.test',to:['reader@skyfirst.io.vn'],subject:'Mail inbound',text:'Hello',messageId:'<inbound-test@example.test>'});const before=db.sql.prepare('SELECT count(*) n FROM messages').get().n;let rejected;for(let i=0;i<2;i++){await app.email({from:'other@example.test',to:'reader@skyfirst.io.vn',headers:new Headers({subject:'Mail inbound',date:'Mon, 05 Oct 2026 10:00:00 +0700','message-id':'<inbound-test@example.test>'}),raw:new Response(raw).body,rawSize:raw.byteLength,setReject:s=>{rejected=s}},env,{});}assert.equal(rejected,undefined);assert.equal(db.sql.prepare('SELECT count(*) n FROM messages').get().n,before+1);assert.equal(db.sql.prepare("SELECT sent_at FROM messages WHERE message_id_header='<inbound-test@example.test>'").get().sent_at,'2026-10-05T03:00:00.000Z')});
 await t.test('cursor pagination does not repeat messages',async()=>{const first=await request('/api/messages?folder=sent&limit=1');assert.equal(first.data.messages.length,1);assert.ok(first.data.nextCursor);const next=await request('/api/messages?folder=sent&limit=1&before='+first.data.nextCursor);assert.notEqual(first.data.messages[0].id,next.data.messages[0].id)});
 await t.test('deleting recipient preserves shared sender MIME',async()=>{const row=db.sql.prepare("SELECT storage_key FROM messages WHERE mailbox_id=1 AND subject='Kiểm thử tiếng Việt' ORDER BY id LIMIT 1").get();const x=await request('/api/admin/users/2','DELETE',{confirmEmail:'reader@skyfirst.io.vn'});assert.equal(x.r.status,200,JSON.stringify(x.data));assert.ok(objects.has(row.storage_key));});
 await t.test('expired session on current day rejected',async()=>{db.sql.exec("UPDATE sessions SET expires_at=strftime('%Y-%m-%dT%H:%M:%fZ','now','-1 minute')");assert.equal((await request('/api/me')).r.status,401)});
 }finally{globalThis.fetch=originalFetch;}
});
test('HTML parser strips executable markup and preserves table formatting',()=>{const clean=cleanEmailHtml('<table><tr><td style="color:red">Xin chào</td></tr></table><img src=x onerror=alert(1)><svg onload=alert(1)><script>x</script></svg><a href="jav&#x61;script:alert(1)">click</a><iframe srcdoc="x"></iframe>');assert.match(clean,/<table>/);assert.match(clean,/color:red/);assert.doesNotMatch(clean,/onerror|onload|javascript:|<script|<svg|<iframe/)});
test('MIME Vietnamese subject and attachment bytes roundtrip',async()=>{const raw=await buildMime({from:'a@example.test',to:['b@example.test'],subject:'Thư tiếng Việt',text:'Xin chào',attachments:[new File(['Dữ liệu'],'data.txt',{type:'text/plain'})]});objects.set('roundtrip',raw);const parsed=await parseStoredMessage(env,'roundtrip');assert.equal(parsed.subject,'Thư tiếng Việt');assert.equal(new TextDecoder().decode(parsed.attachments[0].content),'Dữ liệu')});
